wandb_version: 1

architecture:
  desc: null
  value: RESNET32
dataset:
  desc: null
  value: cub
num_parts:
  desc: null
  value: 8
lr:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 16
image_size:
  desc: null
  value: 448
epoch:
  desc: null
  value: 28
_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710270933.0
    t:
      1:
      - 1
      - 41
      - 51
      - 55
      2:
      - 1
      - 41
      - 51
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.8
      5: 0.16.4
      8:
      - 5
      13: linux-x86_64
